languageCode = "en-us"
title = "Cupper"
baseURL = "https://kerseyi.github.io/cupper-3/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the **Cupper** documentation builder, built with **Cupper** itself."
  codePenUser = "iank"
